### ISSUE TITLE
[Bug]: Can't edit node data

### ISSUE THREAD

**Issue by fabnavigator** [zwave-js/node-red-contrib-zwave-js#234] opened 2022-07-13 16:22 UTC
### What happened?

I upgraded to 7.1.2 and now I get this when I edit any node:

![Untitled](https://user-images.githubusercontent.com/16625904/178782446-42ea45b8-e229-4a58-bc8b-c56b984344df.png)

### How to reproduce?

Edit a node.

### Version

7.1.2

### Node-RED Version

2.2.2-16

### What hardware are you seeing the problem on?

Raspberry Pi

**Comment by marcus-j-davies** [comment] 2022-07-13 16:24
Yup!

it's been fixed in 7.2.0 😄 

I'll close this, as its technically a duplicate of https://github.com/zwave-js/node-red-contrib-zwave-js/issues/231

**Closed by marcus-j-davies** 2022-07-13 16:24 UTC
Labels: bug

**Comment by fabnavigator** [comment] 2022-07-13 16:33
Would it make sense for me to stick with x.x.0 versions for my production system?

**Comment by marcus-j-davies** [comment] 2022-07-13 16:42
I'll be pushing out 7.2.0 in a day or so (maybe Evan this evening, if I can find the energy)

 - The missing `label` bug has been there since I introduced  it `normalizedObject`
 - The bug to show simple message type prompts, was introduced in 7.1.2.
   It only affects node naming and location, and adding associations
