### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fabnavigator** [zwave-js/node-red-contrib-zwave-js#279] opened 2023-07-31 16:20 UTC
### What happened?

The power reporting threshold max value is 50 in the template, but shows as 5 in the node-red-contrib-zwave-js configuration window. See attached template and configuration screen shots.

![template](https://github.com/zwave-js/node-red-contrib-zwave-js/assets/16625904/b0dceae7-0f5a-4bd2-b2e7-05f4f04302bf)

### How to reproduce?

Look at node configuration.

### Version

8.1.0

### Node-RED Version

3.0.2

### What hardware are you seeing the problem on?

Raspberry Pi

### Relevant Z-Wave-JS log as a text file

N/A

**Comment by marcus-j-davies** [comment] 2023-07-31 16:51
Hi @fabnavigator 

its not a bug - this config file was only updated last week - so the one your looking at on Github, is this result of it recently being updated.

https://github.com/zwave-js/node-zwave-js/commit/42c081d320768548b72e5e6e533786473b8ec7ed#diff-1abe48fdc015ac052e52578f2d3032e8be38a778e6f4993c39806d3f52151d71

**Comment by fabnavigator** [comment] 2023-07-31 17:32
@marcus-j-davies, I don't understand. In node-red, It says the maximum is 5, but it accepted 50. Are you saying that it's going to fix itself?

**Comment by marcus-j-davies** [comment] 2023-07-31 17:39
The **Min** / **Max** - is only used so that UI's can create numeric inputs that limits the range - I of course don't (but I should really) @AlCalzone  - is that right (given the driver didn't enforce the max value)?

@fabnavigator 
The config your install has, is using a config file for this device, that was recently updated on the main repo, if there is a new DB (with the changes I linked to)  - you can (on the controller node) check for an updated DB.

I released v8.2.0 the other day - so I may have just missed the recent BD updates, therefore try updating the DB form the controller (if a DB update is available with these changes)

**Comment by marcus-j-davies** [comment] 2023-07-31 18:56
> Am I correct in assuming that the manufacturer doesn't normally do any of these updates to zwave js?

Some do - but a majority of the configuration DB is contributed by the user community.

**Comment by marcus-j-davies** [comment] 2023-07-31 19:03
FWIW - if you wanted to test your work in adding them your self.

 - Create a Directory to hold custom config files
 - Set this directory In the controller (screenshot) - it acts as a priority over the defaults
 - Put In this directory, your patched config file ( you will need to include the templates folder also, if the config file uses it)
 - Restart the controller (renaming it will usually trigger this)
 - in some cases follow up with a device interview (not always)
 
![Screenshot 2023-07-31 at 20 02 09](https://github.com/zwave-js/node-red-contrib-zwave-js/assets/55892693/220f55ac-c17c-4dd1-9950-60a5edfffb4d)

**Comment by AlCalzone** [comment] 2023-07-31 22:15
Our min/max values are meant for the UI, e.g. limiting the range on number input fields. If the value reported by the device is out of range, we don't enforce it to be in the documented range.

So as you already figured out, the config file needs to be updated and/or corrected.

**Comment by fabnavigator** [comment] 2023-07-31 22:23
I'm working on updating the file(s). I have a question. How do I let the user know that  0 = High level, 1 = Mid level, 2 = Low level?

**Comment by AlCalzone** [comment] 2023-07-31 22:26
The `options` property of https://zwave-js.github.io/node-zwave-js/#/config-files/file-format?id=paraminformation

You'll probably want to combine it with `"allowManualEntry": false` to prevent other values from being entered and turn the UI into a dropdown.

**Comment by fabnavigator** [comment] 2023-07-31 22:28
Thanks.  I found an example of that and deleted my question, but you wer too fast with an answer.

**Comment by fabnavigator** [comment] 2023-07-31 22:33
@AlCalzone, I'm seeing a real mixed bag of words starting with an upper case letter. Looks like in this file at least it is usually the case. Would you prefer "Battery report threshold" or "Battery Report Threshold"?

**Comment by fabnavigator** [comment] 2023-07-31 23:09
@marcus-j-davies, Not good. I'm getting ```2023-07-31T23:08:02.762Z DRIVER   Controller identification returned invalid node ID 0```. ANd that's even after I removed the new file and tmeplate.

**Comment by fabnavigator** [comment] 2023-07-31 23:21
I needed to reboot the computer. I had to reinterview the node, and now I can see the additional configuration items.

**Comment by marcus-j-davies** [comment] 2023-08-01 07:42
> @marcus-j-davies, Not good. I'm getting 2023-07-31T23:08:02.762Z DRIVER   Controller identification returned invalid node ID 0. ANd that's even after I removed the new file and tmeplate.

I have never seen this myself, some strange response with the controller @AlCalzone?

I'll close this issue  - given its more a discussion of config updates  - that is already addressed with https://github.com/zwave-js/node-zwave-js/issues/6097

**Closed by marcus-j-davies** 2023-08-01 07:42 UTC
Labels: working-as-intended

**Comment by AlCalzone** [comment] 2023-08-01 08:02
> Would you prefer "Battery report threshold" or "Battery Report Threshold"?

Parameter labels should be **Title Case**, option labels **Sentence case**.

**Comment by fabnavigator** [comment] 2023-08-01 11:29
@AlCalzone, is there an easier way to load changes to the drivers, besides rebooting?

**Comment by marcus-j-davies** [comment] 2023-08-01 11:33
Restarting the controller node destroys the driver instance and starts it back up.

**Comment by marcus-j-davies** [comment] 2023-08-01 11:35
And make sure "Soft Reset USB" is ticked

**Comment by fabnavigator** [comment] 2023-08-01 11:35
@marcus-j-davies, How do I do that?

**Comment by fabnavigator** [comment] 2023-08-01 11:37
@marcus-j-davies , It was not checked, but it is now.

**Comment by fabnavigator** [comment] 2023-08-01 11:59
@marcus-j-davies, How does this work ```"$if": "firmwareVersion >= 1.2",```? It looks like 1.2 is treated as a number not a character string, but version numbers aren't numbers (ie., 1.20.1). If these are just treated as character strings "1.2" is less than "1.10". Right?

**Comment by marcus-j-davies** [comment] 2023-08-01 12:24
It's all driver side config settings.


https://zwave-js.github.io/node-zwave-js/#/config-files/conditional-settings?id=conditional-configuration-settings

**Comment by marcus-j-davies** [comment] 2023-08-01 12:44
Sorry yes (I'm sure) 1.2 is less then 1.10 - I re-call some work was done driver side sometime ago around this. @AlCalzone?

**Comment by AlCalzone** [comment] 2023-08-01 12:48
> "1.2" is less than "1.10"

Correct. The strings in those comparisons are interpreted and compared as versions according to [semver](https://semver.org/#spec-item-11).
